#!/bin/sh

# Installing Oh-my-zsh if not already installed

if [ ! -d "$HOME/.oh-my-zsh/" ]; then
  fancy_echo "Installing Oh My Zsh ..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi
