#!/bin/sh

if [[ -z $ZSH_THEME_EMOJI_PREFIX ]]; then
  EMOJIS=('💩' '🦊' '🚀' '🦄' '👻' '🤖' '🦆' '🦉' '🌮''' '💰' '🔥' '💥' '🍄' '🐙' '🐳' '🌈' '🤷‍♀️')
  ZSH_THEME_EMOJI_PREFIX=${EMOJIS[$(( $RANDOM % ${#EMOJIS[@]} + 1 ))]}
fi

PROMPT='%{$fg_bold[cyan]%}$ZSH_THEME_EMOJI_PREFIX %{$fg_bold[green]%}%p %{$fg[green]%}%c %{$fg_bold[cyan]%}$(git_prompt_info)%{$fg_bold[blue]%} % %{$reset_color%}'
# PROMPT='{NOT SURE}{RANDOM EMOJI }{NOT SURE} {CURRENT DIRECTORY}

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[blue]%}[%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[green]%}] %{$fg[yellow]%}⚡ %{$reset_color%}"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[green]%}]"
