#!/bin/sh

# Install brew if not already installed
if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    append_to_file "$HOME/.zshrc" 'export PATH="/usr/local/bin:$PATH"'
fi

fancy_echo "Updating Homebrew formulas ..."
brew update --verbose

fancy_echo "Brew doctor is verifying the Homebrew installation 🚑..."
if brew doctor; then
  fancy_echo "Your Homebrew installation is good to go."
else
  fancy_echo "Your Homebrew installation reported some errors or warnings."
  echo "If the warnings are related to Python, you can ignore them."
  echo "Otherwise, review the Homebrew messages to see if any action is needed."
fi

fancy_echo "Installing formulas and casks from the Brewfile 🍺..."
brew bundle --file=./run/homebrew/Brewfile

echo "Installing cask apps..."
brew bundle --file=./run/homebrew/brew-casks

read -p "Do you want to install apps from the App Store now? It will require your Apple credentials. [Y/n]: " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "Installing Mas apps, including Xcode. This may take a little while..."
  brew bundle --file=./run/homebrew/brew-mas
fi

read -p "Do you want to install Xcode now? It could take a while. [Y/n]: " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo "Installing Xcode and MacVim..."
  brew bundle --file=./run/homebrew/xcode-install
fi
