#!/bin/sh

if [ ! -f "$HOME/.zsh/antigen/" ]; then
  fancy_echo "Installing the Antigen plugin manager ◬..."
  mkdir ~/.zsh
  curl https://cdn.jsdelivr.net/gh/zsh-users/antigen@v1.2.3/bin/antigen.zsh > ~/.zsh/antigen.zsh

  append_to_file "$HOME/.zshrc" 'ZSH="$HOME/.zsh"'
  append_to_file "$HOME/.zshrc" "source $ZSH/antigen.zsh"

  source ./plugins
else
  echo "Antigen already exsists..."
fi
