#!/bin/sh

fancy_echo 'Checking on Node.js installation...'

if ! command -v nvm > /dev/null; then
  fancy_echo 'Installing nvm and lts Node.js and npm...'

  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash

  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

  fancy_echo 'Installing latests stable version of node...'
  nvm install stable
else
  fancy_echo 'node version manager detected.  Skipping...'
fi

fancy_echo '...Finished Node.js installation checks.'
