set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
  Plugin 'VundleVim/Vundle.vim'
  Plugin 'tpope/vim-fugitive'

  Plugin 'scrooloose/nerdcommenter'
  Plugin 'scrooloose/nerdtree'
  Plugin 'scrooloose/syntastic'
  Plugin 'easymotion/vim-easymotion'
  Plugin 'pangloss/vim-javascript'
  Plugin 'bronson/vim-trailing-whitespace'
  Plugin 'mxw/vim-jsx'
  Plugin 'tpope/vim-surround'
  Plugin 'tpope/vim-markdown'
  Plugin 'bling/vim-airline'
  Plugin 'kien/ctrlp.vim'
  Plugin 'elzr/vim-json'
  Plugin 'ap/vim-css-color'
call vundle#end()

filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" shows relative line number and current line number.
set relativenumber
set number

" make tabs spaces
set expandtab
set tabstop=2
set shiftwidth=2

" Adds mouse functionality in all modes
set mouse=a

" clear all trailing whitespace
nmap <leader>nw :FixWhitespace<CR>

nnoremap cp :set invpaste paste?<CR>
set pastetoggle=cp
set showmode

" NERDtree
let g:NERDTreeWinPos = "left"
let g:NERDTreeWinSize = 21
" open nerd tree w ctrl n
nmap <C-n> :NERDTreeToggle<CR>

" Press i to enter insert mode, and ii to exit.
:imap ii <Esc>

if has("autocmd")
  autocmd! bufwritepost .vimrc source $MYVIMRC
endif

nmap <leader>v :tabedit $MYVIMRC<CR>
