set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
  Plugin 'VundleVim/Vundle.vim'

  Plugin 'scrooloose/nerdcommenter'
  Plugin 'scrooloose/nerdtree'
  Plugin 'scrooloose/syntastic'
  Plugin 'easymotion/vim-easymotion'
  Plugin 'edkolev/tmuxline.vim'
  Plugin 'pangloss/vim-javascript'
  Plugin 'bronson/vim-trailing-whitespace'
  Plugin 'mxw/vim-jsx'
  Plugin 'nathanaelkane/vim-indent-guides'
  Plugin 'tpope/vim-surround'
  Plugin 'tpope/vim-markdown'
  Plugin 'tpope/vim-fugitive'
  Plugin 'airblade/vim-gitgutter'
  Plugin 'bling/vim-airline'
  Plugin 'kien/ctrlp.vim'
  Plugin 'elzr/vim-json'
  Plugin 'ap/vim-css-color'
  Plugin 'valloric/youcompleteme'
call vundle#end()

filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" shows relative line number and current line number.
set relativenumber
set number

" make tabs spaces
set expandtab
set tabstop=2
set shiftwidth=2

" Copy to system clipboard
:set clipboard=unnamed

" Turn on syntax highlighting.
syntax on

" Adds mouse functionality in all modes
set mouse=a

" clear all trailing whitespace
nmap <leader>nw :FixWhitespace<CR>

nnoremap cp :set invpaste paste?<CR>
set pastetoggle=cp
set showmode

" Airline, always show airline bar
set laststatus=2
let g:airline_powerline_fonts = 1

let g:tmuxline_preset = 'nightly_fox'

" NERDtree
let g:NERDTreeWinPos = "left"
let g:NERDTreeWinSize = 21

" open NERDTree w ctrl \
nmap <C-\> :NERDTreeToggle<CR>

" CTRLP ignore files
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'

" Toggles indent guides
nmap <leader>dn :IndentGuidesToggle<CR>

" jj to exit INSERT mode.
:imap jj <Esc>

if has("autocmd")
  autocmd! bufwritepost .vimrc source $MYVIMRC
endif

" Open this file from any vim session.
nmap <leader>v :tabedit $MYVIMRC<CR>

" Line number gutter colors
highlight LineNr ctermfg=57 ctermbg=233 guifg=Purple guibg=DarkGray
highlight SignColumn ctermbg=233 guibg=DarkGray


