set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

" alternatively, Vundle where to install plugins vundle#begin('~/some/path/here')
call vundle#begin()
" Keep Plugin commands between vundle#begin/end.
" The following are examples of different formats supported.

Plugin 'VundleVim/Vundle.vim'                 " let Vundle manage Vundle, required
Plugin 'tpope/vim-fugitive'                   " plugin on GitHub repo
Plugin 'git://git.wincent.com/command-t.git'  " Git plugin not hosted on GitHub
Plugin 'file:///home/gmarik/path/to/plugin'   " git repos on your local machine (i.e. when working on your own plugin)
"
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

" End sample plugins - All your Plugins must be added before vundle#end()

Plugin 'scrooloose/nerdtree'

call vundle#end()            " required

filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on

" HELP
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ


" Put your non-Plugin stuff after this line
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set relativenumber

" Tabs
set expandtab       " Make tabs spaces
set tabstop=2       " Set tabs to 2 spaces
set shiftwidth=2
