#!/bin/sh

fancy_echo "Setting up Tmux..."

ln -s ~/projects/dotfiles/run/tmux/tmux.conf ~/.tmux.conf
ln -s ~/projects/dotfiles/run/tmux/web-env ~/.tmux.web-env
ln -s ~/projects/dotfiles/run/tmux/dev-env ~/.tmux.dev-env

# Install Powerline fonts
git clone https://github.com/powerline/fonts ~/Library/fonts/
~/Library/Fonts/./install.sh

echo "Follow directions in README to finalize Powerline fonts config..."
